/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as BookShowIdRouteImport } from './routes/book.$showId'
import { Route as BookingBookingIdRouteImport } from './routes/booking.$bookingId'
import { Route as ConfirmationBookingIdRouteImport } from './routes/confirmation.$bookingId'
import { Route as MovieMovieIdRouteImport } from './routes/movie.$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const BookShowIdRoute = BookShowIdRouteImport.update({
  id: '/book/$showId',
  path: '/book/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationBookingIdRoute = ConfirmationBookingIdRouteImport.update({
  id: '/confirmation/$bookingId',
  path: '/confirmation/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/my-bookings': typeof MyBookingsRoute
  '/payment': typeof PaymentRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/book/$showId': typeof BookShowIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/my-bookings': typeof MyBookingsRoute
  '/payment': typeof PaymentRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/book/$showId': typeof BookShowIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRoute
  '/my-bookings': typeof MyBookingsRoute
  '/payment': typeof PaymentRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/book/$showId': typeof BookShowIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/movies'
    | '/my-bookings'
    | '/payment'
    | '/signup'
    | '/summary'
    | '/book/$showId'
    | '/booking/$bookingId'
    | '/confirmation/$bookingId'
    | '/movie/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/movies'
    | '/my-bookings'
    | '/payment'
    | '/signup'
    | '/summary'
    | '/book/$showId'
    | '/booking/$bookingId'
    | '/confirmation/$bookingId'
    | '/movie/$movieId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/movies'
    | '/my-bookings'
    | '/payment'
    | '/signup'
    | '/summary'
    | '/book/$showId'
    | '/booking/$bookingId'
    | '/confirmation/$bookingId'
    | '/movie/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MoviesRoute: typeof MoviesRoute
  MyBookingsRoute: typeof MyBookingsRoute
  PaymentRoute: typeof PaymentRoute
  SignupRoute: typeof SignupRoute
  SummaryRoute: typeof SummaryRoute
  BookShowIdRoute: typeof BookShowIdRoute
  BookingBookingIdRoute: typeof BookingBookingIdRoute
  ConfirmationBookingIdRoute: typeof ConfirmationBookingIdRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$showId': {
      id: '/book/$showId'
      path: '/book/$showId'
      fullPath: '/book/$showId'
      preLoaderRoute: typeof BookShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$bookingId': {
      id: '/confirmation/$bookingId'
      path: '/confirmation/$bookingId'
      fullPath: '/confirmation/$bookingId'
      preLoaderRoute: typeof ConfirmationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MoviesRoute: MoviesRoute,
  MyBookingsRoute: MyBookingsRoute,
  PaymentRoute: PaymentRoute,
  SignupRoute: SignupRoute,
  SummaryRoute: SummaryRoute,
  BookShowIdRoute: BookShowIdRoute,
  BookingBookingIdRoute: BookingBookingIdRoute,
  ConfirmationBookingIdRoute: ConfirmationBookingIdRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
